### PR TITLE
Make example program fully buildable

### PR DESCRIPTION
**Pull request by virtualsue**
Just a suggestion - I find it's nice to have an example program that can be copied/run.

### CODE REVIEW

**Comment by elithrar** [comment]
Hey @virtualsue - sorry for the slow reply. 

The example in your PR won't be buildable via a copy+paste as it's not a valid Go program. For it to be buildable it's best to just put this into a `main()` function - although that won't reflect the typical use of the library.

If you can:

* Update it so it runs in the playground 
* Check the errors (might as well - sets a good example for others)

... I'll merge it in. 

Thanks!

**Comment by virtualsue** [comment]
The goal I had in mind was not to have an entirely valid Go program in the comments. Just something a bit closer to that so fiddling would be at a minimum when initially trying out your code. For example, Perl module documentation - at least on some of the better modules - refers to this as a 'synopsis'. It's not the full program, just a really easy to use chunk that a reasonably adept user can dump into a file and see how it works.  In other words, no I won't go right the way down the street and turn it into a full playground-able program ;-)

**Comment by elithrar** [comment]
Alright, thanks. If you're okay with it, I've forked your PR [here](https://github.com/gorilla/feeds/pull/23) and have corrected the example so it's runnable. The major issue was the invalid package declaration: `package main {` (with the opening brace) isn't valid Go.

Figured since we're updating it might as well go the extra step :smile: 

Let me know if you're happy for me to build on your PR.

**Comment by elithrar** [comment]
Going to merge this. Please let me know if this becomes an issue.

**Pull request merged**
