### PR TITLE
Add Custom Fields

### PR DESCRIPTION
**Pull request by njones**
This is a pull request that addresses issue #25.

### CODE REVIEW

**Comment by kisielk** [comment]
I guess we will need to drop go1.7 support in order to include this. @elithrar do you think it's too soon to do that, or probably fine? It's almost 2 years old now

**Comment by elithrar** [comment]
Yes, we should require 1.7 and cut a new release for that, as well as
update the Travis config to match.

**Comment by kisielk** [comment]
You mean require 1.8? That seems to be the earliest version with `xml.Attr`

**Comment by elithrar** [comment]
Yes, sorry! 1.8+ is fine. We’re at 1.10 and 1.11 in August.

**Comment by njones** [comment]
Cool! I just realized that I need to comment the functions for the GoDoc, so I'll do that and make another commit. 

Feel free to request any other changes.

**Comment by kisielk** [comment]
Great. I just updated `.travis.yml` in master so if you could also rebase so the tests run properly that would be great.

**Pull request closed without merging**
