### PR TITLE
support added for Source field in RSS

### PR DESCRIPTION
**Pull request by milanaleksic**
This is a very small change, but allows a legacy iOS application I am a server for to be able to digest the RSS coming from my server, since the iOS app demands that item field `Source` exists on the server side.

### CODE REVIEW

**Comment by milanaleksic** [comment]
The `go tool vet` is now standard part of the go distribution so no need to fetch it any more from golang.org (it failed travis build), so I fixed that also in this PR

**Comment by kisielk** [comment]
Thanks. Since you're updating `travis.yml` can you also add go1.7 and go1.8 there?

**Comment by milanaleksic** [comment]
Done

**Comment by kisielk** [comment]
Thanks :)

**Pull request merged**
