### PR TITLE
feat: support JSON Feed 1.1 closes #91

### LINKED ISSUE #91: [feature] Support JSON feed v1.1
**Is your feature request related to a problem? Please describe.**
[The JSON feed spec is currently at v1.1](https://jsonfeed.org/version/1.1). The changes from v1.0 to v1.1 are very minor, so this should be a pretty easy box to check off.

**Describe the solution you'd like**
Here's a synopsis of changes, taken from the specification:
> **Version 1.1 — 8/7/2020:**
>- Updated to use more specific `application/feed+json` MIME type.
>- Added `authors` field to allow more than 1 author per feed or item. Deprecated `author`.
>- Added `language` field.
>- Clarified that `id` should be a string.
>- Updated links to JSON and other specs.

### PR DESCRIPTION
**Pull request by meblum**
## What type of PR is this? (check all applicable)

- [x] Feature

## Related Tickets & Documents
closes #91

## Added/updated tests?

- [x] Yes

### CODE REVIEW

**Review by AlexVulaj — APPROVED** [review]
Thanks for pulling this in, looks good to me

**Comment by meblum** [comment]
@AlexVulaj Thanks for merging! Can we please have a new tagged release published? Given that we now generate JSON Feed 1.1 and have fixed that issue that could cause panics, I think it makes sense to create a new tag so consumers of the module will benefit of these updates.

**Comment by AlexVulaj** [comment]
@meblum we're discussing what we want our release process to look like currently, but this repo will be one of the first to go once that's squared away!

**Comment by meblum** [comment]
I appreciate that, thank you!

**Pull request merged**
