### PR TITLE
Don't create an empty <summary> in Atom feeds

### LINKED ISSUE #82: Spurious empty <summary> elements in atom feed
I have a feed in which items have a non-empty Content but an empty Description. This should result in an atom feed with a `<content>` element for the item but no `<summary>` element, but it seems that the feeds package always emits a `<summary>` element, even if it is empty.

https://play.golang.org/p/gE3aNOkeIqb

The feeds package should not should not emit a `<summary>` element if `Item.Content` is set but `Item.Description` is blank. Its presence may mislead feed readers into displaying the (empty) summary, ignoring the post content.

I'm currently working around the issue like this, but would prefer if this wasn't necessary. 

	atomFeed := (&feeds.Atom{feed}).AtomFeed()
	for i := range atomFeed.Entries {
		atomFeed.Entries[i].Summary = nil
	}

**Versions**
> Go version: `go version go1.14.3 linux/amd64`
> package version: `6f6e20dd3953594cd869cf981fb806440685cd21`

**Steps to Reproduce**
> How can the bug be triggered?

See code snippet below.

<details><summary>Output:</summary>

```
<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom">
  <title>A blog</title>
  <id>http://example.net/</id>
  <updated>2009-11-10T23:00:00Z</updated>
  <link href="http://example.net/"></link>
  <author>
    <name>Test User</name>
    <email>foo@example.net</email>
  </author>
  <entry>
    <title>Blog post</title>
    <updated>2009-11-10T23:00:00Z</updated>
    <id>tag:example.net,2009-11-10:/1</id>
    <content type="html">Full contents of the blog post</content>
    <link href="http://example.net/1" rel="alternate"></link>
    <summary type="html"></summary>
    <author>
      <name>Test User</name>
      <email>test@example.net</email>
    </author>
  </entry>
</feed>
```

</details>

**Expected behavior**

> What output or behaviour were you expecting instead?

<details><summary>Expected output</summary>

```
<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom">
  <title>A blog</title>
  <id>http://example.net/</id>
  <updated>2009-11-10T23:00:00Z</updated>
  <link href="http://example.net/"></link>
  <author>
    <name>Test User</name>
    <email>foo@example.net</email>
  </author>
  <entry>
    <title>Blog post</title>
    <updated>2009-11-10T23:00:00Z</updated>
    <id>tag:example.net,2009-11-10:/1</id>
    <content type="html">Full contents of the blog post</content>
    <link href="http://example.net/1" rel="alternate"></link>
    <author>
      <name>Test User</name>
      <email>test@example.net</email>
    </author>
  </entry>
</feed>
```

</details>

**Code Snippets**

https://play.golang.org/p/gE3aNOkeIqb

```
package main

import (
	"log"
	"os"
	"time"

	"github.com/gorilla/feeds"
)

func main() {
	now := time.Now()
	feed := &feeds.Feed{
		Title:   "A blog",
		Link:    &feeds.Link{Href: "http://example.net/"},
		Author:  &feeds.Author{Name: "Test User", Email: "foo@example.net"},
		Created: now,
	}

	feed.Items = []*feeds.Item{
		&feeds.Item{
			Title:   "Blog post",
			Link:    &feeds.Link{Href: "http://example.net/1"},
			Content: "Full contents of the blog post",
			Author:  &feeds.Author{Name: "Test User", Email: "test@example.net"},
			Created: now,
		},
	}

	err := feed.WriteAtom(os.Stdout)
	if err != nil {
		log.Fatal(err)
	}
}
```

### PR DESCRIPTION
**Pull request by magical**
When creating an AtomEntry from an Item, only set Summary if
item.Description is non-empty, like we already do for Content.

Currently we always emit a `<summary>` element, even if the item has a
non-empty `<content>` element. Having an empty `<summary>` in this case may
be confusing for feed consumers.

The Atom RFC explicitly says that a `<summary>` is not required in general.
(There are a couple special cases where it is required, but they aren't
relevant here.)

https://tools.ietf.org/html/rfc4287#section-4.1.1.1

Fixes #82

### CODE REVIEW

**Comment by magical** [comment]
ping @elithrar

**Comment by magical** [comment]
Not stale.

**Comment by magical** [comment]
Still not stale.

**Comment by magical** [comment]
Poke

**Comment by magical** [comment]
Bump

**Comment by magical** [comment]
poke

**Comment by magical** [comment]
👋

**Comment by glacials** [comment]
> The Atom RFC explicitly says that a \<summary\> is not required in general.
> (There are a couple special cases where it is required, but they aren't
> relevant here.)

This one seems maybe relevant, since the consumer can set the `Type`:

> atom:entry elements MUST contain an atom:summary element in either
>       of the following cases:
> ...
> *  the atom:entry contains content that is encoded in Base64; i.e., the "type" attribute of atom:content is a MIME media type [[MIMEREG](https://datatracker.ietf.org/doc/html/rfc4287#ref-MIMEREG)], but is not an XML media type [[RFC3023](https://datatracker.ietf.org/doc/html/rfc3023)], does not begin with "text/", and does not end with "/xml" or "+xml".

**Review by amustaque97 — APPROVED** [review]
Thanks for making that change. Also kudos for your effort to keep commenting on both issue and PR to avoid staleness. 

cc @elithrar, merge this PR.

**Comment by felicianotech** [comment]
Hey @magical,

In case you haven't seen, Gorilla has abandoned all of their projects. There is a note about it on the readme. I needed a library like this and after some research, this one seemed to fit the build even though it is abandoned. So, I have forked the project and it can be found here: https://github.com/gopherlibs/feedhub

I would appreciate it if you were willing to recreate this PR over at my fork and submit a PR. Havening looked at the PR here, I am confident we can get it merged into my fork.

p.s. You snagged the GitHub username `magical`? Nice.

**Review by milosgajdos — APPROVED** [review]

**Review by coreydaley — APPROVED** [review]

**Comment by magical** [comment]
@coreydaley Thanks!

**Pull request merged**
